### ISSUE TITLE
Compatibility issue with the latest version a QGIS

### ISSUE THREAD

**Issue by francis33** [PANOimagen/batch_hillshader#9]
Hello,

Since I recently updated QGIS (version (3.14.15), I can't load anymore the plugin at the lauching of QGIS.

I get the message : 

Impossible de charger l'extension 'batch_hillshader-master' provoque une erreur lors de l'appel à sa méthode classFactory() 

ImportError: DLL load failed: Le module spécifié est introuvable. 

Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Cascade Interchange/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_hillshader-master\__init__.py", line 47, in classFactory
    from .batch_hillshader import batchHillshader
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Cascade Interchange/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_hillshader-master\batch_hillshader.py", line 45, in 
    from .batch_hillshader_dialog import batchHillshaderDialog
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Cascade Interchange/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_hillshader-master\batch_hillshader_dialog.py", line 53, in 
    from . import laspy_utils
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Cascade Interchange/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_hillshader-master\laspy_utils.py", line 38, in 
    from scipy.interpolate import griddata
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\scipy\interpolate\__init__.py", line 167, in 
    from .interpolate import *
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\scipy\interpolate\interpolate.py", line 15, in 
    import scipy.special as spec
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\scipy\special\__init__.py", line 634, in 
    from . import _ufuncs
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: Le module spécifié est introuvable.

Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.14.15-Pi Pi, d5114d2cfa 
Chemin Python :
- C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python
- C:/Users/Cascade Interchange/AppData/Roaming/QGIS/QGIS3\profiles\default/python
- C:/Users/Cascade Interchange/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
- C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins
- C:\PROGRA~1\QGIS3~1.14\apps\Python37
- C:\PROGRA~1\QGIS3~1.14\apps\Python37\Scripts
- C:\Program Files\QGIS 3.14\bin\python37.zip
- C:\PROGRA~1\QGIS3~1.14\apps\Python37\DLLs
- C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib
- C:\Program Files\QGIS 3.14\bin
- C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages
- C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\win32
- C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\win32\lib
- C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\Pythonwin
- C:/Users/Cascade Interchange/AppData/Roaming/QGIS/QGIS3\profiles\default/python
- C:\Users\Cascade Interchange\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs
- C:/Users/Cascade Interchange/Documents/00. Centre de données/10. QGIS Projects

Is it a problem with my computer ?
Does the plugin need to evoluate ?

Thanks
Francis

**Comment by abdulhafidz6** [comment]
Hi, I have the same problem too. 
I already upgraded the dependency libraries, but still not working in QGIS 3.14.15. I also have installed QGIS 3.10 before and it is working in there. I wish it is working in the latest QGIS 3.16.

**Comment by dieza** [comment]
Similar error here, 

No s'ha pogut carregar el complement 'batch_hillshader-master' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'gdal' 
Traceback (most recent call last):
  File "/Applications/QGIS-Dev.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/castella/python/plugins/batch_hillshader-master/__init__.py", line 47, in classFactory
    from .batch_hillshader import batchHillshader
  File "/Applications/QGIS-Dev.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/castella/python/plugins/batch_hillshader-master/batch_hillshader.py", line 45, in 
    from .batch_hillshader_dialog import batchHillshaderDialog
  File "/Applications/QGIS-Dev.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/castella/python/plugins/batch_hillshader-master/batch_hillshader_dialog.py", line 53, in 
    from . import laspy_utils
  File "/Applications/QGIS-Dev.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/castella/python/plugins/batch_hillshader-master/laspy_utils.py", line 40, in 
    from gdal import gdalconst
  File "/Applications/QGIS-Dev.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'gdal'


Versió phyton: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
Versió del QGIS: 3.23.0-Master Master, 0bab0122f8 



Versió del QGIS | 3.23.0-Master | Revisió del codi QGIS | 0bab0122f8
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.0
  |   |   |  
Active Python plugins
leastcostpath | 1.0
clusterpoints | 4.11
FreehandRasterGeoreferencer | 0.8.3
attributeBasedClustering | 2.2
LCPNetwork | version 0.1.5
AGT | 3.1.2
VectorBender | 0.2.1
AzimuthMeasurement | 0.2.2
quick_map_services | 0.19.26
IPyConsole | version 2.0
track_profile_2_web | 1.3
Anaximandre | 1.2
nominatim | 1.4.1
QPackage | 1.5
ArcheoCAD | 3.1.1
LAStools | 1.4
SRTM-Downloader | 3.1.15
BivariateLegend | 1.0.2
ViewshedAnalysis | 1.7
rvt-qgis | 0.8.0
latlontools | 3.5.9
networks | 2.5.16
processing_r | 3.0.0
group_transparency | 0.2
ProfileFromPoints | 3.1
TerrainShading | 0.9
Qgis2threejs | 2.6
OSMDownloader | 1.0.3
qgsAzimuth | 0.9.15
qgis_resource_sharing | 0.16.0
VoGisProfilTool | 3.0.2
pointsamplingtool | 0.5.3
lizmap | 3.6.3
qgis_preview_mode_plugin | 0.1.0
open_lidar_tools | 2.1
mmqgis | 2021.9.10
shapetools | 3.4.1
WaterNetAnalyzer-master | 1.7
mapswipetool_plugin | 1.2
ClassificationTool | 0.2
Mergin | 2021.4.2
ForestRoadsNetworksUPLOAD | 1.6
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

**Comment by JaviBecerra** [comment]
This is likely the same issue as #10/#11, should be fixed with version 2.4.3.
